### ISSUE TITLE
Uppercase extension

### ISSUE THREAD

**Issue by albatros69** [jeffwidman/flask-uploads#22]
Currently, it someone tries to upload a file with an uppercase extension (.JPG), he might end up with an Exception "not allowed", except if the app has explicitly authorized it.

I would assume that a non-case sensitive test on the extension makes sense.

**Comment by albatros69** [comment]
Sorry, completely irrelevant...
I overlooked something obvious!

**Comment by jeffwidman** [comment]
No worries, thanks for following up with your solution.
