### ISSUE TITLE
Werkzeug Error

### ISSUE THREAD

**Issue by mrsaicharan1** [jeffwidman/flask-uploads#25]
the `secure_filename` module has moved over from `werkzeug.py to werkzeug/utils.py`. Alluding to this, the core uploads are not working. Would be happy to fix it.

**Comment by jeffwidman** [comment]
You're probably using a different `flask-uploads`, this one isn't the one on `pypi` (it was supposed to be, but then the original maintainer had given the creds to someone else who refused to transfer them... long story).

Sorry for the hassle. I'll archive this repo to reduce the confusion, so please email me if you're actually using this repo's code.

**Comment by jeffwidman** [comment]
Actually, on second thought, I'm going to just delete this repo... the name clash will never be resolved, and I haven't used it in years.
